# fly.toml app configuration file generated for carnegie on 2023-08-06T21:04:35-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "carnegie"
primary_region = "sea"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build.args]
  NEXT_PUBLIC_API_URL="https://carnegie-api.fly.dev"
  NEXT_PUBLIC_FE_URL="https://carnegie.fly.dev/api/proxy"